language: cpp
sudo: required
dist: trusty
services:
  - docker
before_install:
  - docker build -t remko/dicewords .
script:
  - docker run remko/dicewords /bin/sh -c "cd /opt/src && make CXX=g++ check"
